project:
  type: website
  output-dir: "docs"
website:
  title: "Kiran Gaha"
  navbar:
    left:
    - text: "Home"
      file: index.qmd
    - text: "Portfolio"
      file: portfolio.qmd
    - text: "Resume"
      file: resume.qmd
 
format:
  html:
    theme: sketchy
    css: styles.css

editor: visual

